all: partA partB partC partD partE
partA:
	gcc partA.c -o partA
partB:
	gcc partB.c -o partB
partC:
	gcc partC.c -o partC
partD:
	gcc partD.c -o partD
partE:
	gcc partE.c -o partE
clean:
	rm partA partB partC partD partE
