function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 13-Jan-2017 00:07:10

% Create figure
figure1 = figure('Color',...
    [0.905882358551025 0.905882358551025 0.905882358551025]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to semilogy
semilogy1 = semilogy(X1,YMatrix1,'Marker','.','Parent',axes1);
set(semilogy1(1),'DisplayName','4-PSK with Gray');
set(semilogy1(2),'DisplayName','4-PSK without Gray','Color',[1 0 0]);
set(semilogy1(3),'DisplayName','8-PSK with Gray','Color',[0 0 1]);
set(semilogy1(4),'DisplayName','8-PSK without Gray',...
    'Color',[0.24705882370472 0.24705882370472 0.24705882370472]);

% Create xlabel
xlabel('SNR/bit, dB','FontSize',11);

% Create title
title('Bit Rate Error','FontSize',11);

% Create ylabel
ylabel('BER','FontSize',11);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'Color',[0.972549021244049 0.972549021244049 0.972549021244049],...
    'XGrid','on','YGrid','on','YMinorTick','on','YScale','log');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Color',[1 1 1]);

